# Generated by Django 3.0.5 on 2020-04-25 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('login', models.CharField(max_length=25, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='country',
            name='users',
            field=models.ManyToManyField(to='locations.User'),
        ),
    ]
